export const MISC_FOLLOW = 'MISC_FOLLOW';
export const MISC_UNFOLLOW = 'MISC_UNFOLLOW';
export const MISC_NOTIFS = 'MISC_NOTIFS';
export const MISC_REPORT = 'MISC_REPORT';
export const MISC_START = 'MISC_START';
export const MISC_FAIL = 'MISC_FAIL';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const USER_ITEM = 'USER_ITEM';

export const ITEM_START = 'ITEM_START';
export const ITEM_SUCCESS = 'ITEM_SUCCESS';
export const ITEM_SINGLE_SUCCESS = 'ITEM_SINGLE_SUCCESS';
export const ITEM_FAIL = 'ITEM_FAIL';

export const ITEM_POST_SUCCESS = 'ITEM_POST_SUCCESS';

export const ITEM_EDIT_SUCCESS = 'ITEM_EDIT_SUCCESS';

export const ITEM_DEL_SUCCESS = 'ITEM_DEL_SUCCESS';

export const ITEM_SELLINI_SUCCESS = 'ITEM_SELLINI_SUCCESS';

export const ITEM_SELLFIN_SUCCESS = 'ITEM_SELLFIN_SUCCESS';

export const ITEM_REPORT_SUCCESS = 'ITEM_REPORT_SUCCESS';
export const ITEM_RESOLVE_SUCCESS = 'ITEM_RESOLVE_SUCCESS';

export const REVIEW_START = 'REVIEW_START';
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS';
export const REVIEW_FAIL = 'REVIEW_FAIL';

export const REVIEW_POST_START = 'REVIEW_POST_START';
export const REVIEW_POST_SUCCESS = 'REVIEW_POST_SUCCESS';

export const REVIEW_EDIT_START = 'REVIEW_EDIT_START';
export const REVIEW_EDIT_SUCCESS = 'REVIEW_EDIT_SUCCESS';

export const REVIEW_DEL_START = 'REVIEW_DEL_START';
export const REVIEW_DEL_SUCCESS = 'REVIEW_DEL_SUCCESS';

export const REVIEW_UPVOTE_SUCCESS = 'REVIEW_UPVOTE_SUCCESS';
export const REVIEW_DOWNVOTE_SUCCESS = 'REVIEW_DOWNVOTE_SUCCESS';

export const REVIEW_REPORT_SUCCESS = 'REVIEW_REPORT_SUCCESS';
export const REVIEW_RESOLVE_SUCCESS = 'REVIEW_RESOLVE_SUCCESS';

export const CHAT_USER_STACK = 'CHAT_USER_STACK';
export const CHAT_USER_PSTACK = 'CHAT_USER_PSTACK';
export const CHAT_USER_CHATS = 'CHAT_USER_CHATS';
export const CHAT_USER_CHATS_INIT = 'CHAT_USER_CHATS_INIT';
export const CHAT_UPDATE_MSG = 'CHAT_UPDATE_MSG';
export const CHAT_ROOM_SET = 'CHAT_ROOM_SET';
export const CHAT_ROOM_MESSAGE = 'CHAT_ROOM_MESSAGE';
export const CHAT_ROOM_READ = 'CHAT_ROOM_READ';
export const SOCKET_MOUNT = 'SOCKET_MOUNT';
export const SOCKET_UNMOUNT = 'SOCKET_UNMOUNT';
export const SOCKET_ERR = 'SOCKET_ERR';
